/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  QueryModel,
  SubmitQueryRequest,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    QueryModelFromJSON,
    QueryModelToJSON,
    SubmitQueryRequestFromJSON,
    SubmitQueryRequestToJSON,
} from '../models/index';

export interface GetQueryByIdQueryGetRequest {
    queryId: string;
}

export interface GetUserQueriesUsersUserIdQueriesGetRequest {
    userId: string;
}

export interface SubmitQueryQueryPostRequest {
    submitQueryRequest: SubmitQueryRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Get Query By Id
     */
    async getQueryByIdQueryGetRaw(requestParameters: GetQueryByIdQueryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueryModel>> {
        if (requestParameters['queryId'] == null) {
            throw new runtime.RequiredError(
                'queryId',
                'Required parameter "queryId" was null or undefined when calling getQueryByIdQueryGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['queryId'] != null) {
            queryParameters['query_id'] = requestParameters['queryId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/query`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueryModelFromJSON(jsonValue));
    }

    /**
     * Get Query By Id
     */
    async getQueryByIdQueryGet(requestParameters: GetQueryByIdQueryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryModel> {
        const response = await this.getQueryByIdQueryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get User Queries
     */
    async getUserQueriesUsersUserIdQueriesGetRaw(requestParameters: GetUserQueriesUsersUserIdQueriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<QueryModel>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserQueriesUsersUserIdQueriesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{user_id}/queries`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QueryModelFromJSON));
    }

    /**
     * Get User Queries
     */
    async getUserQueriesUsersUserIdQueriesGet(requestParameters: GetUserQueriesUsersUserIdQueriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<QueryModel>> {
        const response = await this.getUserQueriesUsersUserIdQueriesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index
     */
    async indexGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Index
     */
    async indexGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.indexGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Submit Query
     */
    async submitQueryQueryPostRaw(requestParameters: SubmitQueryQueryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueryModel>> {
        if (requestParameters['submitQueryRequest'] == null) {
            throw new runtime.RequiredError(
                'submitQueryRequest',
                'Required parameter "submitQueryRequest" was null or undefined when calling submitQueryQueryPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/query`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmitQueryRequestToJSON(requestParameters['submitQueryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueryModelFromJSON(jsonValue));
    }

    /**
     * Submit Query
     */
    async submitQueryQueryPost(requestParameters: SubmitQueryQueryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryModel> {
        const response = await this.submitQueryQueryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
